import { readdirSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import { compile, DIAGNOSTIC_CODES, format } from "@sysarch/core";
import MarkdownIt from "markdown-it";
import { describe, expect, it } from "vitest";
import { isDiagram } from "../.vitepress/blocks.mjs";

// Keeps the hand-written documentation in sync with the code. Whatever can be generated from
// the code is generated by scripts/generate.ts; this is about the rest.

const DOCS = join(import.meta.dirname, "..");
const ROOT = join(DOCS, "../..");
const read = (path: string) => readFileSync(join(ROOT, path), "utf8");
const page = (path: string) => readFileSync(join(DOCS, path), "utf8");
const strings = (source: string, pattern: RegExp) => [...source.matchAll(pattern)].map((m) => m[1]!);

/** Hand-written pages — without the generated directories. */
function pages(dir = DOCS): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    if (entry.name.startsWith(".") || entry.name.startsWith("_") || ["node_modules", "public", "concept", "test", "scripts"].includes(entry.name)) return [];
    const path = join(dir, entry.name);
    return entry.isDirectory() ? pages(path) : entry.name.endsWith(".md") ? [relative(DOCS, path)] : [];
  });
}

describe("Reference diagnostics", () => {
  it("has a section for every diagnostic code", () => {
    const headings = strings(page("reference/diagnostics.md"), /^## (\S+)$/gm);
    expect(headings).toEqual([...DIAGNOSTIC_CODES]);
  });
});

describe("Obsidian guide", () => {
  const text = page("guides/obsidian.md");
  const sources = ["main.ts", "settings.ts", "block.ts", "exports.ts", "library-view.ts"]
    .map((file) => read(`apps/obsidian/src/${file}`)).join("\n");

  it("names every command", () => {
    for (const name of strings(sources, /addCommand\(\{[^}]*?name: "([^"]+)"/gs)) expect(text, name).toContain(`**${name}**`);
  });

  it("names every setting", () => {
    for (const name of strings(sources, /\.setName\("([^"]+)"\)/g)) expect(text, name).toContain(`**${name}**`);
  });

  it("names every menu entry", () => {
    for (const title of strings(sources, /\.setTitle\("([^"]+)"\)/g)) expect(text, title).toContain(`**${title}**`);
  });
});

describe("Web app guide", () => {
  it("names every button", () => {
    const text = page("guides/web-app.md");
    const html = read("apps/web/index.html");
    for (const label of strings(html, /<button[^>]*>([^<]+)<\/button>/g)) expect(text, label).toContain(`**${label}**`);
  });
});

describe("Reference CLI", () => {
  it("explains every option", () => {
    const text = page("reference/cli.md");
    for (const option of new Set(strings(read("apps/cli/src/cli.ts"), /(?<![\w-])(--[a-z][a-z-]+)/g))) {
      expect(text.replace(/<!--@include:[^>]*-->/g, ""), option).toContain(`\`${option}`);
    }
  });
});

describe("Navigation", () => {
  const config = readFileSync(join(DOCS, ".vitepress/config.mts"), "utf8");
  const links = strings(config, /link: "(\/[^"]*)"/g);
  const target = (link: string) => (link.endsWith("/") ? `${link.slice(1)}index.md` : `${link.slice(1)}.md`);

  it("links only to pages that exist", () => {
    const concept = readdirSync(join(ROOT, "docs")).map((f) => `concept/${f}`);
    for (const link of links) {
      const file = target(link);
      if (file === "concept/index.md") continue;
      expect([...pages(), ...concept], link).toContain(file);
    }
  });

  it("contains every page", () => {
    const linked = new Set(links.map(target));
    for (const file of pages().filter((f) => f !== "index.md")) expect(linked, file).toContain(file);
  });
});

describe("Diagrams in the documentation", () => {
  const md = new MarkdownIt({ html: true });
  const diagrams = pages().flatMap((file) =>
    md.parse(page(file), {})
      .filter((t) => t.type === "fence" && t.info.trim() === "sysarch" && isDiagram(t.content))
      .map((t) => ({ where: `${file}:${(t.map?.[0] ?? 0) + 1}`, code: t.content })),
  );

  it("exist", () => {
    expect(diagrams.length).toBeGreaterThan(10);
  });

  it("are free of errors and warnings", () => {
    for (const { where, code } of diagrams) {
      const shown = compile(code).diagnostics.filter((d) => d.severity !== "info");
      expect(shown.map((d) => `${d.code} ${d.message}`), where).toEqual([]);
    }
  });

  it("are canonically formatted", () => {
    for (const { where, code } of diagrams) expect(format(code).value, where).toBe(code);
  });
});
